FROM node:20-alpine3.18 AS base

FROM base AS deps
WORKDIR /app
COPY ./package.json ./package.json
COPY ./yarn.lock ./yarn.lock
RUN yarn

FROM base AS runner
WORKDIR /app
COPY . .
COPY --from=deps /app/node_modules ./node_modules
RUN yarn global add dotenv-cli
